export default {
  login: "Strand-Made",
  id: 60408983,
  node_id: "MDQ6VXNlcjYwNDA4OTgz",
  avatar_url: "https://avatars.githubusercontent.com/u/60408983?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Strand-Made",
  html_url: "https://github.com/Strand-Made",
  followers_url: "https://api.github.com/users/Strand-Made/followers",
  following_url:
    "https://api.github.com/users/Strand-Made/following{/other_user}",
  gists_url: "https://api.github.com/users/Strand-Made/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Strand-Made/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Strand-Made/subscriptions",
  organizations_url: "https://api.github.com/users/Strand-Made/orgs",
  repos_url: "https://api.github.com/users/Strand-Made/repos",
  events_url: "https://api.github.com/users/Strand-Made/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Strand-Made/received_events",
  type: "User",
  site_admin: false,
  name: "Stian",
  company: null,
  blog: "",
  location: "Bodø",
  email: null,
  hireable: null,
  bio: "Frontend development student \r\nNoroff",
  twitter_username: null,
  public_repos: 19,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-01-28T21:26:08Z",
  updated_at: "2021-05-12T20:12:19Z",
};
